set :domain, 'alpha.jumpstart.ge'
set :user, 'prisoners-staging'
set :application, 'Starter-Template-Staging'
set :repository, 'git@github.com:JumpStartGeorgia/Starter-Template.git'
set :web_url, 'dev-rails4-deploy.jumpstart.ge'